apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-notas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-notas
  template:
    metadata:
      labels:
        app: ms-notas
    spec:
      containers:
      - name: ms-notas
        image: ghcr.io/willrem001-beep/sistema-educativo-ci-cd/ms-notas:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        env:
        - name: DB_HOST
          value: "db-postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "db_notas"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-password