apiVersion: v1
kind: Service
metadata:
  name: ms-notas-service
spec:
  type: NodePort
  selector:
    app: ms-notas
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30003
  type: NodePort