#version: '3.8'

services:
  # BASE DE DATOS: POSTGRESQL
  db-postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init-db-postgres.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  # BASE DE DATOS: MONGODB
  db-mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      retries: 5

  # MICROSERVICIO 1: USUARIOS
  servicio-usuarios:
    build: ./Microserv_Users
    container_name: ms-usuarios
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db-postgres
      DB_PORT: 5432
      DB_NAME: db_usuarios
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db-postgres:
        condition: service_healthy

  # MICROSERVICIO 2: TAREAS
  servicio-tareas:
    build: ./Microserv_Tareas
    container_name: ms-tareas
    ports:
      - "3002:3002"
    environment:
      MONGO_URI: mongodb://db-mongo:27017/db_tareas
    depends_on:
      db-mongo:
        condition: service_healthy

  # MICROSERVICIO 3: NOTAS
  servicio-notas:
    build: ./Microserv_Notas
    container_name: ms-notas
    ports:
      - "3003:3003"
    environment:
      DB_HOST: db-postgres
      DB_PORT: 5432
      DB_NAME: db_notas
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${NOTAS_DB_PASSWORD}
    depends_on:
      db-postgres:
        condition: service_healthy

  # MICROSERVICIO 4: ASISTENCIA
  servicio-asistencia:
    build: ./Microserv_Asistencias
    container_name: ms-asistencia
    ports:
      - "3004:3004"
    environment:
      MONGO_URI: mongodb://db-mongo:27017/db_asistencia
    depends_on:
      db-mongo:
        condition: service_healthy

   # LOKI
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    # Usamos el config default interno, no necesitamos montar un archivo externo para empezar
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  # MONITOREO: PROMTAIL
  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    
  # MONITOREO: GRAFANA
  grafana:
    image: grafana/grafana:11.2.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki
      - prometheus
    restart: unless-stopped
  
  # MONITOREO: PROMETHEUS
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    # Añadimos depends_on para intentar conectar después de que inicien los microservicios
    depends_on:
      - servicio-usuarios
      - servicio-tareas
      - servicio-notas
      - servicio-asistencia
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: unless-stopped

volumes:
  postgres-data:
  mongo-data:
  loki-data:
  grafana-data:
  prometheus_data: