version: '3.8'

services:
  # BASE DE DATOS: POSTGRESQL
  db-postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init-db-postgres.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  # BASE DE DATOS: MONGODB
  db-mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      retries: 5

  # MICROSERVICIO 1: USUARIOS
  servicio-usuarios:
    build: ./Microserv_Users
    container_name: ms-usuarios
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db-postgres
      DB_PORT: 5432
      DB_NAME: db_usuarios
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db-postgres:
        condition: service_healthy

  # MICROSERVICIO 2: TAREAS
  servicio-tareas:
    build: ./Microserv_Tareas
    container_name: ms-tareas
    ports:
      - "3002:3002"
    environment:
      MONGO_URI: mongodb://db-mongo:27017/db_tareas
    depends_on:
      db-mongo:
        condition: service_healthy

  # MICROSERVICIO 3: NOTAS
  servicio-notas:
    build: ./Microserv_Notas
    container_name: ms-notas
    ports:
      - "3003:3003"
    environment:
      DB_HOST: db-postgres
      DB_PORT: 5432
      DB_NAME: db_notas
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${NOTAS_DB_PASSWORD}
    depends_on:
      db-postgres:
        condition: service_healthy

  # MICROSERVICIO 4: ASISTENCIA
  servicio-asistencia:
    build: ./Microserv_Asistencias
    container_name: ms-asistencia
    ports:
      - "3004:3004"
    environment:
      MONGO_URI: mongodb://db-mongo:27017/db_asistencia
    depends_on:
      db-mongo:
        condition: service_healthy

  # LOKI
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  # PROMTAIL
  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  postgres-data:
  mongo-data: