global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'tesis-final'

scrape_configs:
  # Prometheus mismo
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Microservicio de Usuarios
  - job_name: 'ms-usuarios'
    scrape_interval: 5s # Escaneo rápido para ver cambios
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.49.2:30001']
        labels:
          app: 'usuarios'
          origen: 'minikube-nodeport'

  # Microservicio de Tareas
  - job_name: 'ms-tareas'
    scrape_interval: 5s # Escaneo rápido para ver cambios
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.49.2:30002']
        labels:
          app: 'tareas'
          origen: 'minikube-nodeport'

  # Microservicio de Notas
  - job_name: 'ms-notas'
    scrape_interval: 5s # Escaneo rápido para ver cambios
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.49.2:30003']
        labels:
          app: 'notas'
          origen: 'minikube-nodeport'

  # Microservicio de Asistencia
  - job_name: 'ms-asistencia'
    scrape_interval: 5s # Escaneo rápido para ver cambios
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.49.2:30004']
        labels:
          app: 'asistencia'
          origen: 'minikube-nodeport'

  # Frontend
  - job_name: 'ms-frontend'
    scrape_interval: 5s # Escaneo rápido para ver cambios
    metrics_path: '/metrics'
    static_configs:
      - targets: ['192.168.49.2:30080']
        labels:
          app: 'frontend'
          origen: 'minikube-nodeport'