global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'tesis-final'

scrape_configs:
  # 1. Prometheus (Se auto-monitoriza)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Microservicio de Usuarios
  # IMPORTANTE: Usa la IP de Minikube y el NodePort (30001)
  - job_name: 'ms-usuarios'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.49.2:30001']
        labels:
          app: 'usuarios'

  # 3. Microservicio de Tareas (Puerto 30002)
  - job_name: 'ms-tareas'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.49.2:30002']
        labels:
          app: 'tareas'

  # 4. Microservicio de Notas (Puerto 30003)
  - job_name: 'ms-notas'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.49.2:30003']
        labels:
          app: 'notas'

  # 5. Microservicio de Asistencia (Puerto 30004)
  - job_name: 'ms-asistencia'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.49.2:30004']
        labels:
          app: 'asistencia'

  # 6. Frontend (Puerto 30005 - Asumido basado en tu lista de svc)
  - job_name: 'ms-frontend'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.49.2:30005']
        labels:
          app: 'frontend'