apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ms-usuarios
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: ms-usuarios
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s