apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-frontend
spec:
  replicas: 2 # 2 réplicas del Frontend
  selector:
    matchLabels:
      app: ms-frontend
  template:
    metadata:
      labels:
        app: ms-frontend
    spec:
      containers:
      - name: ms-frontend
        image: ghcr.io/willrem001-beep/sistema-educativo-ci-cd/ms-frontend:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 80