global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'tesis-final'

scrape_configs:
  # 1. Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. MICROSERVICIOS (usando nombres internos del clúster)
  - job_name: 'ms-usuarios'
    metrics_path: /metrics
    static_configs:
      - targets: ['ms-usuarios:3001']
        labels:
          app: 'usuarios'

  - job_name: 'ms-tareas'
    metrics_path: /metrics
    static_configs:
      - targets: ['ms-tareas:3002']
        labels:
          app: 'tareas'

  - job_name: 'ms-notas'
    metrics_path: /metrics
    static_configs:
      - targets: ['ms-notas:3003']
        labels:
          app: 'notas'

  - job_name: 'ms-asistencia'
    metrics_path: /metrics
    static_configs:
      - targets: ['ms-asistencia:3004']
        labels:
          app: 'asistencia'

  - job_name: 'ms-frontend'
    metrics_path: /metrics
    static_configs:
      - targets: ['ms-frontend:80']
        labels:
          app: 'frontend'

  # CADVISOR
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # NODE EXPORTER
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
      
  # KUBE-STATE-METRICS
  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['prometheus-kube-state-metrics.monitoring.svc.cluster.local:8080']
    scrape_interval: 15s