apiVersion: v1
kind: Service
metadata:
  name: ms-asistencia-service
spec:
  type: NodePort
  selector:
    app: ms-asistencia
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
      nodePort: 30004