apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-frontend
spec:
  replicas: 2 # 2 réplicas del Frontend
  selector:
    matchLabels:
      app: ms-frontend
  template:
    metadata:
      labels:
        app: ms-frontend
    spec:
      containers:
      - name: ms-frontend
        image: ghcr.io/TU_USUARIO/TU_REPO/ms-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80