apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: postgres-password
        volumeMounts:
        # Montamos sobre la carpeta de inicialización, no sobre el archivo
        - name: init-db
          mountPath: /docker-entrypoint-initdb.d
        # montaje para que los datos se guarden permanentemente
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data 
      volumes:
      - name: init-db
        configMap:
          name: postgres-configmap
          #volumen para que los datos no se borren tras un reinicio
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: pvc-postgres-data