apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  init.sql: |
    CREATE DATABASE db_usuarios;
    CREATE DATABASE db_notas;
    GRANT ALL PRIVILEGES ON DATABASE db_usuarios TO ms_admin;
    GRANT ALL PRIVILEGES ON DATABASE db_notas TO ms_admin;
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MONGO_URI: "mongodb://mongo-service:27017"
  NODE_ENV: "development"