apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/postgres
  - ../../base/mongo
  - ../../base/usuarios
  - ../../base/tareas
  - ../../base/notas
  - ../../base/asistencia
  - ../../base/frontend

patches:
  - path: nodeport-patches.yaml  # Para los NodePorts

secretGenerator:
  - name: db-secrets
    files:
      - secrets/db-secret.env
  - name: jwt-secrets
    files:
      - secrets/jwt-secret.env

configMapGenerator:
  - name: app-config
    files:
      - configmap.yaml