apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-usuarios
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-usuarios
  template:
    metadata:
      labels:
        app: ms-usuarios
    spec:
      containers:
      - name: ms-usuarios
        image: ghcr.io/willrem001-beep/sistema-educativo-ci-cd/ms-usuarios:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: "db-postgres-service"  # Nombre del servicio K8s
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "db_usuarios"
        - name: JWT_EXPIRES_IN
          value: "3h"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: db-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: jwt-secret