apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-tareas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-tareas
  template:
    metadata:
      labels:
        app: ms-tareas
      annotations:
        prometheus.io/scrape: "true"    
        prometheus.io/port: "3002"      
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: ms-tareas
        image: ghcr.io/willrem001-beep/sistema-educativo-ci-cd/ms-tareas:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/db_tareas"
        volumeMounts:
        - name: uploads-storage
          mountPath: /app/uploads
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: pvc-tareas-uploads