name: CI/CD Microservices Kubernetes

on:
push:
branches: [ "main" ]

env:
REGISTRY: ghcr.io

jobs:

# JOB 1: BUILD & PUSH (IMAGENES)

build-and-push:
runs-on: ubuntu-latest
permissions:
contents: read
packages: write

```
strategy:
  matrix:
    include:
      - service: ms-usuarios
        path: ./Microserv_Users
      - service: ms-tareas
        path: ./Microserv_Tareas
      - service: ms-notas
        path: ./Microserv_Notas
      - service: ms-asistencia
        path: ./Microserv_Asistencias
      - service: ms-frontend
        path: ./frontend-tesis

steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Login GHCR
    uses: docker/login-action@v3
    with:
      registry: ${{ env.REGISTRY }}
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

  - name: Build & Push
    uses: docker/build-push-action@v5
    with:
      context: ${{ matrix.path }}
      push: true
      tags: |
        ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.service }}:${{ github.sha }}
        ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.service }}:latest
```

# JOB 2: DEPLOY A KUBERNETES (MINIKUBE)


deploy:
runs-on: self-hosted
needs: build-and-push

```
steps:
  - name: Checkout
    uses: actions/checkout@v4

  - name: Verificar cluster
    shell: powershell
    run: |
      kubectl get nodes

  # ACTUALIZAR FRONTEND
  - name: Deploy Frontend
    shell: powershell
    run: |
      kubectl set image deployment/ms-frontend ms-frontend=ghcr.io/${{ github.repository }}/ms-frontend:${{ github.sha }}
      kubectl rollout status deployment/ms-frontend

  # ACTUALIZAR USUARIOS
  - name: Deploy Usuarios
    shell: powershell
    run: |
      kubectl set image deployment/ms-usuarios ms-usuarios=ghcr.io/${{ github.repository }}/ms-usuarios:${{ github.sha }}
      kubectl rollout status deployment/ms-usuarios

  # ACTUALIZAR TAREAS
  - name: Deploy Tareas
    shell: powershell
    run: |
      kubectl set image deployment/ms-tareas ms-tareas=ghcr.io/${{ github.repository }}/ms-tareas:${{ github.sha }}
      kubectl rollout status deployment/ms-tareas

  # ACTUALIZAR NOTAS
  - name: Deploy Notas
    shell: powershell
    run: |
      kubectl set image deployment/ms-notas ms-notas=ghcr.io/${{ github.repository }}/ms-notas:${{ github.sha }}
      kubectl rollout status deployment/ms-notas

  # ACTUALIZAR ASISTENCIA
  - name: Deploy Asistencia
    shell: powershell
    run: |
      kubectl set image deployment/ms-asistencia ms-asistencia=ghcr.io/${{ github.repository }}/ms-asistencia:${{ github.sha }}
      kubectl rollout status deployment/ms-asistencia

  # 🔍 DEBUG FINAL
  - name: Verificar estado final
    shell: powershell
    run: |
      kubectl get pods
```
